import { useEffect, useMemo, useRef, useState, type JSX } from 'react'
import * as monaco from 'monaco-editor'
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker'
import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker'
import { useHang4r } from '../state/store'
import { resolveTheme, isDarkTheme } from '../theme'
import type { SettingsScope } from '../../../shared/protocol'
import { stripJsonComments } from '../../../shared/jsonc'

/* Monaco's workers are wired globally by CodeEditor; set a JSON/editor fallback
 * here too so this surface works even before the code editor has ever mounted. */
const env = self as unknown as { MonacoEnvironment?: monaco.Environment }
if (!env.MonacoEnvironment) {
  env.MonacoEnvironment = {
    getWorker(_id, label) {
      return label === 'json' ? new jsonWorker() : new editorWorker()
    }
  }
}

/* JSON-schema hover + validation for the two settings files. Keyed by model URI
 * so the app file and a workspace file each get the right shape.
 *
 * These are also the SINGLE SOURCE OF TRUTH for the "All available settings"
 * reference panel below — it's generated by walking these objects (see
 * `flattenSchemas`), so the panel can never drift from what Monaco actually
 * validates/autocompletes against. Every property here must carry a
 * `description`; add a `default` only when a real built-in default exists
 * (verified against settingsService / its consumers, not guessed). */
const AGENT_DEFAULTS = {
  type: 'object',
  description: 'Per-backend agent defaults.',
  properties: {
    model: {
      type: 'string',
      description:
        'Pre-fills the New Agent dialog with this model when this backend is selected (applies at New Agent).'
    },
    permissionMode: {
      type: 'string',
      enum: ['acceptEdits', 'default', 'plan', 'bypassPermissions'],
      description:
        'Pre-fills the New Agent dialog with this permission mode when this backend is selected (applies at New Agent).'
    }
  },
  additionalProperties: false
} as const

const NOTIFICATIONS = {
  type: 'object',
  description: 'Per-event OS notification toggles (workspace file overrides the app default).',
  properties: {
    onActionRequired: {
      type: 'boolean',
      default: true,
      description: 'Notify when a session starts waiting on a permission decision.'
    },
    onError: {
      type: 'boolean',
      default: true,
      description: 'Notify when a turn ends in error.'
    }
  },
  additionalProperties: false
} as const

const APP_SCHEMA = {
  type: 'object',
  description: 'hang4r app-global settings (~/.hang4r/settings.json).',
  properties: {
    theme: {
      type: 'string',
      enum: ['system', 'dark', 'light', 'nord', 'solarized'],
      default: 'system',
      description: 'UI theme. "system" follows the OS light/dark preference.'
    },
    editorFontSize: {
      type: 'number',
      default: 12,
      description: 'Monaco editor font size (px).'
    },
    chatFontSize: {
      type: 'number',
      default: 13,
      description: 'Conversation font size (px).'
    },
    terminalShell: {
      type: 'string',
      description: 'Shell for new terminals (blank = the system default shell).'
    },
    terminalKeymap: {
      type: 'array',
      description:
        'iTerm2-style key mappings (blank/unset = the built-in "natural" keymap defaults).'
    },
    notifyOnComplete: {
      type: 'boolean',
      default: true,
      description: 'Notify when an agent finishes in the background.'
    },
    notifications: NOTIFICATIONS,
    defaultModel: {
      type: 'string',
      description:
        'Pre-fills the New Agent dialog with this model (blank = choose per session) (applies at New Agent).'
    },
    defaultPermissionMode: {
      type: 'string',
      enum: ['acceptEdits', 'default', 'plan', 'bypassPermissions'],
      default: 'acceptEdits',
      description:
        'Pre-fills the New Agent dialog with this permission mode for new sessions (applies at New Agent).'
    },
    defaultEnvironment: {
      type: 'string',
      enum: ['worktree', 'local'],
      default: 'worktree',
      description:
        'Pre-fills the New Agent dialog with this environment (isolated worktree or the local checkout) for new sessions (applies at New Agent).'
    },
    binaries: {
      type: 'object',
      description: 'Explicit CLI binary paths (blank = auto-detect).',
      properties: {
        claude: {
          type: 'string',
          description: 'Explicit path to the claude CLI binary (blank = auto-detect on PATH).'
        },
        codex: {
          type: 'string',
          description: 'Explicit path to the codex CLI binary (blank = auto-detect on PATH).'
        },
        cursor: {
          type: 'string',
          description: 'Explicit path to the cursor-agent CLI binary (blank = auto-detect on PATH).'
        }
      },
      additionalProperties: false
    },
    worktreeDir: {
      type: 'string',
      default: '.hang4r-worktrees',
      description: 'Global worktree container folder, relative to each repo.'
    },
    worktreeBranchPrefix: {
      type: 'string',
      default: '',
      description:
        'Optional namespace for worktree branches (e.g. "agents/"). Blank (default): the branch is exactly the session name, no prefix.'
    },
    setupScript: {
      type: 'string',
      description:
        'Global new-worktree setup script. Runs via your login shell in each fresh worktree; ROOT_WORKTREE_PATH = main repo.'
    },
    sshHosts: {
      type: 'array',
      default: [],
      description: 'Registered SSH remote hosts.'
    },
    agents: {
      type: 'object',
      description: 'Per-backend defaults (workspace file overrides these).',
      properties: {
        claude: AGENT_DEFAULTS,
        codex: AGENT_DEFAULTS,
        cursor: AGENT_DEFAULTS
      },
      additionalProperties: false
    }
  }
} as const

const WORKSPACE_SCHEMA = {
  type: 'object',
  description: 'hang4r per-workspace overrides (<project>/.hang4r/settings.json).',
  properties: {
    worktreeDir: {
      type: 'string',
      default: '.hang4r-worktrees',
      description: 'Worktree container folder for this repo (overrides the app default).'
    },
    worktreeBranchPrefix: {
      type: 'string',
      description:
        'Branch namespace for this repo\'s worktrees (e.g. "agents/"; overrides the app default). Blank: branch = session name.'
    },
    setupScript: {
      type: 'string',
      description: 'New-worktree setup script for this repo (overrides the app default).'
    },
    terminalShell: {
      type: 'string',
      description: 'Shell override for this workspace (blank = falls back to the app setting).'
    },
    notifications: NOTIFICATIONS,
    devProcesses: {
      type: 'array',
      default: [],
      description: 'Processes tab: dev/service commands started per session.',
      items: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Label shown for this process in the Processes tab.' },
          command: { type: 'string', description: 'Shell command run to start this process.' },
          autoStart: {
            type: 'boolean',
            default: false,
            description:
              'Start with every new session (worktrees wait for the setup script first). Default: only the Start button runs it.'
          }
        },
        additionalProperties: false
      }
    },
    agents: {
      type: 'object',
      description: 'Per-backend overrides for this workspace (overrides the app agents defaults).',
      properties: {
        claude: AGENT_DEFAULTS,
        codex: AGENT_DEFAULTS,
        cursor: AGENT_DEFAULTS
      },
      additionalProperties: false
    }
  }
} as const

const APP_URI = monaco.Uri.parse('inmemory://hang4r/app.settings.json')
const WORKSPACE_URI = monaco.Uri.parse('inmemory://hang4r/workspace.settings.json')

let schemasRegistered = false
function ensureSchemas(): void {
  if (schemasRegistered) return
  schemasRegistered = true
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const json = (monaco.languages as any).json
  if (!json?.jsonDefaults) return
  json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    // settings files are JSONC-tolerant (the workspace template ships fully
    // commented); the main-side parser strips comments before JSON.parse.
    allowComments: true,
    schemas: [
      {
        uri: 'https://hang4r.dev/schema/app-settings.json',
        fileMatch: [APP_URI.toString()],
        schema: APP_SCHEMA
      },
      {
        uri: 'https://hang4r.dev/schema/workspace-settings.json',
        fileMatch: [WORKSPACE_URI.toString()],
        schema: WORKSPACE_SCHEMA
      }
    ]
  })
  /* eslint-enable @typescript-eslint/no-explicit-any */
}

/* ---------- reference panel: generated FROM the schema objects above ---------- */

type SchemaNode = {
  type?: string
  description?: string
  default?: unknown
  enum?: readonly unknown[]
  properties?: Record<string, SchemaNode>
  items?: SchemaNode
}

interface SettingRow {
  path: string
  type: string
  description: string
  hasDefault: boolean
  default?: unknown
  scope: 'app' | 'workspace' | 'both'
}

function typeLabel(node: SchemaNode): string {
  if (node.enum) return node.enum.map(String).join(' | ')
  return node.type ?? 'any'
}

function placeholderFor(node: SchemaNode): unknown {
  if (node.default !== undefined) return node.default
  if (node.enum && node.enum.length) return node.enum[0]
  switch (node.type) {
    case 'string':
      return ''
    case 'number':
      return 0
    case 'boolean':
      return true
    case 'array':
      return []
    case 'object':
      return {}
    default:
      return null
  }
}

interface WalkedNode {
  type: string
  description: string
  default?: unknown
  hasDefault: boolean
  node: SchemaNode
}

/** Recursively collect every property path from one schema into `out`. */
function walkSchema(schema: SchemaNode, prefix: string, out: Map<string, WalkedNode>): void {
  const props = schema.properties
  if (!props) return
  for (const [key, child] of Object.entries(props)) {
    const path = prefix ? `${prefix}.${key}` : key
    out.set(path, {
      type: typeLabel(child),
      description: child.description ?? '',
      default: child.default,
      hasDefault: child.default !== undefined,
      node: child
    })
    if (child.type === 'object' && child.properties) {
      walkSchema(child, path, out)
    } else if (child.type === 'array' && child.items?.type === 'object' && child.items.properties) {
      walkSchema(child.items, `${path}[]`, out)
    }
  }
}

/** Merge the app + workspace schemas into one deduped, sorted reference list. */
function flattenSchemas(): SettingRow[] {
  const app = new Map<string, WalkedNode>()
  const workspace = new Map<string, WalkedNode>()
  walkSchema(APP_SCHEMA, '', app)
  walkSchema(WORKSPACE_SCHEMA, '', workspace)

  const paths = new Set([...app.keys(), ...workspace.keys()])
  const rows: SettingRow[] = []
  for (const path of paths) {
    const a = app.get(path)
    const w = workspace.get(path)
    const scope: SettingRow['scope'] = a && w ? 'both' : a ? 'app' : 'workspace'
    const primary = a ?? w!
    const description =
      a && w && a.description !== w.description
        ? `${a.description} (workspace: ${w.description})`
        : primary.description
    rows.push({
      path,
      type: primary.type,
      description,
      hasDefault: (a?.hasDefault || w?.hasDefault) ?? false,
      default: a?.default ?? w?.default,
      scope
    })
  }
  rows.sort((x, y) => x.path.localeCompare(y.path))
  return rows
}

/** Build a mergeable JSON snippet (nested per dotted path) for clipboard copy. */
function snippetFor(row: SettingRow): string {
  const segments = row.path.split('.')
  const placeholder = placeholderFor({
    type: row.type.includes(' | ') ? 'string' : row.type,
    default: row.default,
    enum: row.type.includes(' | ') ? row.type.split(' | ') : undefined
  })
  let value: unknown = placeholder
  for (let i = segments.length - 1; i >= 0; i--) {
    let seg = segments[i]
    if (seg.endsWith('[]')) {
      seg = seg.slice(0, -2)
      value = [value]
    }
    value = { [seg]: value }
  }
  return JSON.stringify(value, null, 2)
}

let cachedRows: SettingRow[] | null = null
function allSettingRows(): SettingRow[] {
  if (!cachedRows) cachedRows = flattenSchemas()
  return cachedRows
}

/* ---------- commented workspace template (empty-state for a workspace file) ---------- */

/** A representative example value for a schema node, recursing into objects and
 *  array items so nested shapes (agents.claude.model, devProcesses[]) render. */
function exampleValue(node: SchemaNode): unknown {
  if (node.enum && node.enum.length) return node.enum[0]
  if (node.default !== undefined) return node.default
  switch (node.type) {
    case 'object': {
      const o: Record<string, unknown> = {}
      if (node.properties)
        for (const [k, child] of Object.entries(node.properties)) o[k] = exampleValue(child)
      return o
    }
    case 'array':
      return node.items ? [exampleValue(node.items)] : []
    case 'string':
      return ''
    case 'number':
      return 0
    case 'boolean':
      return true
    default:
      return null
  }
}

/**
 * The fully-commented seed shown (and written by "Create file") for a workspace
 * scope with no `.hang4r/settings.json` yet. Generated by walking
 * WORKSPACE_SCHEMA — the same source the reference panel and Monaco validation
 * use — so it can never drift. Every key is commented out, so the file parses
 * as an empty `{}` until the user opts into an override.
 */
export function workspaceTemplate(): string {
  const lines: string[] = ['{']
  lines.push('  // Per-workspace hang4r settings for THIS repo (safe to commit).')
  lines.push('  //')
  lines.push('  // COMMENTS: your comments are preserved everywhere. Hand-edits here, this')
  lines.push('  // editor’s "Create file"/"Save file" button, and the Settings UI’s Worktrees')
  lines.push('  // tab (when it saves a per-workspace value) all patch this file in place —')
  lines.push('  // your notes and formatting are kept; only the changed value is rewritten.')
  lines.push('  //')
  lines.push('  // Every setting below is commented out; uncomment a line and edit its value')
  lines.push('  // to override the app default for this workspace.')
  lines.push('')

  const props = WORKSPACE_SCHEMA.properties as Record<string, SchemaNode>
  const entries = Object.entries(props)
  entries.forEach(([key, node], idx) => {
    if (node.description) lines.push(`  // ${key} — ${node.description}`)
    const accepts = node.enum ? node.enum.map((v) => JSON.stringify(v)).join(' | ') : node.type
    let acceptLine = `  //   Accepts: ${accepts}.`
    if (node.default !== undefined) acceptLine += ` Default: ${JSON.stringify(node.default)}.`
    lines.push(acceptLine)

    const rendered = JSON.stringify(exampleValue(node), null, 2).split('\n')
    rendered.forEach((line, i) => {
      const tail = i === rendered.length - 1 ? ',' : ''
      lines.push(i === 0 ? `  // "${key}": ${line}${tail}` : `  // ${line}${tail}`)
    })
    if (idx < entries.length - 1) lines.push('')
  })

  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function SettingsReference(): JSX.Element {
  // collapsed by default so the Monaco editor above it owns the full height;
  // it's a lookup drawer, opened on demand via the labelled toggle.
  const [open, setOpen] = useState(false)
  const [filter, setFilter] = useState('')
  const [copied, setCopied] = useState<string | null>(null)
  const rows = allSettingRows()

  const filtered = useMemo(() => {
    const q = filter.trim().toLowerCase()
    if (!q) return rows
    return rows.filter(
      (r) => r.path.toLowerCase().includes(q) || r.description.toLowerCase().includes(q)
    )
  }, [rows, filter])

  const copy = (row: SettingRow): void => {
    void navigator.clipboard.writeText(snippetFor(row)).then(() => {
      setCopied(row.path)
      setTimeout(() => setCopied((c) => (c === row.path ? null : c)), 1500)
    })
  }

  return (
    <div className="settings-json-reference">
      <button
        type="button"
        className="settings-json-reference-toggle"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
      >
        {open ? '▾' : '▸'} All available settings ({rows.length})
      </button>
      {open && (
        <div className="settings-json-reference-body">
          <input
            className="field settings-json-reference-filter"
            placeholder="Filter settings…"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
          />
          <div className="settings-json-reference-list">
            {filtered.map((row) => (
              <button
                type="button"
                key={row.path}
                className="settings-json-reference-row"
                onClick={() => copy(row)}
                title="Click to copy a JSON snippet for this key"
              >
                <span className="settings-json-reference-key">
                  {row.path}
                  <span className={`settings-json-reference-scope scope-${row.scope}`}>
                    {row.scope}
                  </span>
                </span>
                <span className="settings-json-reference-desc">
                  {row.description}
                  {row.hasDefault && (
                    <span className="settings-json-reference-default">
                      {' '}
                      default: {JSON.stringify(row.default)}
                    </span>
                  )}
                </span>
                {copied === row.path && <span className="settings-json-reference-copied">Copied ✓</span>}
              </button>
            ))}
            {filtered.length === 0 && (
              <div className="settings-json-reference-empty">No settings match “{filter}”.</div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

/**
 * In-app JSON editor for a settings.json file. Settings files live OUTSIDE any
 * session worktree, so the session-scoped file IPC can't reach them — this uses
 * a dedicated settings-file IPC and a self-contained Monaco JSON model with a
 * registered schema (hover docs + inline validation), saving with a clear error
 * when the JSON doesn't parse.
 */
export function SettingsJsonEditor({
  scope,
  projectId
}: {
  scope: SettingsScope
  projectId?: string
}): JSX.Element {
  const hostRef = useRef<HTMLDivElement | null>(null)
  const edRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const theme = useHang4r((s) => s.theme)
  const [status, setStatus] = useState<{ kind: 'idle' | 'saved' | 'error'; msg?: string }>({
    kind: 'idle'
  })
  const [path, setPath] = useState('')
  // true when the buffer is the generated template for a not-yet-created file —
  // drives the "Create file" (vs "Save file") button label.
  const [isTemplate, setIsTemplate] = useState(false)

  useEffect(() => {
    ensureSchemas()
    const host = hostRef.current
    if (!host) return
    const uri = scope === 'app' ? APP_URI : WORKSPACE_URI
    let model = monaco.editor.getModel(uri)
    if (!model) model = monaco.editor.createModel('{}', 'json', uri)
    const editor = monaco.editor.create(host, {
      model,
      language: 'json',
      automaticLayout: true,
      minimap: { enabled: false },
      fontSize: 13,
      lineNumbers: 'on',
      scrollBeyondLastLine: false,
      // JSON keys are quoted strings — Monaco's default quickSuggestions
      // suppresses auto-popup inside strings, which hid completion entirely.
      quickSuggestions: { other: true, comments: false, strings: true },
      suggestOnTriggerCharacters: true,
      theme: isDarkTheme(resolveTheme(theme)) ? 'vs-dark' : 'vs'
    })
    edRef.current = editor

    void window.hang4r.settingsFilePath(scope, projectId).then((p) => setPath(p ?? ''))
    void window.hang4r.readSettingsFile(scope, projectId).then((text) => {
      const trimmed = text.trim()
      // An empty workspace file (absent, or a bare `{}`) opens with the fully
      // commented, schema-generated template instead of a lonely `{}`.
      if (scope === 'workspace' && (trimmed === '' || trimmed === '{}')) {
        model!.setValue(workspaceTemplate())
        setIsTemplate(true)
      } else {
        model!.setValue(text)
        setIsTemplate(false)
      }
    })

    return () => {
      editor.dispose()
      // keep the model around (reused across opens); don't dispose it
    }
    // re-init when the target file changes
  }, [scope, projectId]) // eslint-disable-line react-hooks/exhaustive-deps

  // follow the app theme
  useEffect(() => {
    monaco.editor.setTheme(isDarkTheme(resolveTheme(theme)) ? 'vs-dark' : 'vs')
  }, [theme])

  const save = async (): Promise<void> => {
    const text = edRef.current?.getValue() ?? ''
    try {
      JSON.parse(stripJsonComments(text)) // fail fast (JSONC-tolerant) before hitting disk
    } catch (e) {
      setStatus({ kind: 'error', msg: `Invalid JSON — ${(e as Error).message}` })
      return
    }
    try {
      await window.hang4r.writeSettingsFile(scope, text, projectId)
      setIsTemplate(false) // file now exists on disk
      setStatus({ kind: 'saved' })
      setTimeout(() => setStatus({ kind: 'idle' }), 2000)
    } catch (e) {
      setStatus({ kind: 'error', msg: (e as Error).message })
    }
  }

  return (
    <div className="settings-json-editor">
      <div className="settings-json-path" title={path}>
        {path || '(no file for this scope)'}
      </div>
      <p className="settings-json-hint">⌃Space lists valid keys · hover a key for docs</p>
      <div className="settings-json-host" ref={hostRef} />
      <div className="settings-json-actions">
        {status.kind === 'saved' && <span className="settings-saved">Saved ✓</span>}
        {status.kind === 'error' && <span className="settings-json-err">{status.msg}</span>}
        <button className="primary-btn" onClick={() => void save()}>
          {isTemplate ? 'Create file' : 'Save file'}
        </button>
      </div>
      <SettingsReference />
    </div>
  )
}
