import { test, expect } from '@playwright/test'
import { launchApp, makeScratchRepo, createProject, type LaunchedApp } from './helpers'

/**
 * "All available settings" reference panel (round 12 ①): the settings.json
 * editor's schema-driven autocomplete/hover already existed but was invisible.
 * This panel is generated by walking the same schema objects Monaco validates
 * against (src/renderer/src/components/SettingsJsonEditor.tsx), so it can never
 * list something the editor doesn't actually support.
 */
test.describe('settings.json reference panel', () => {
  let launched: LaunchedApp | undefined

  test.afterEach(async () => {
    await launched?.app.close()
    launched = undefined
  })

  test('lists known keys with descriptions, filters, and shows correct scope tagging', async () => {
    launched = await launchApp()
    const { page } = launched
    const repo = makeScratchRepo()
    // Bypass the native folder picker via the exposed IPC, then reload so the
    // store re-fetches projects (the settings.json scope dropdown needs this).
    await createProject(page, repo)
    await page.reload()
    await page.waitForSelector('.app')

    await page.keyboard.press('Meta+k')
    await page.locator('.palette-input').fill('settings')
    await page.locator('.palette-input').press('Enter')
    await expect(page.locator('.settings-page')).toBeVisible()
    await page.locator('.settings-nav-item', { hasText: 'settings.json' }).click()

    const panel = page.locator('.settings-json-reference')
    await expect(panel).toBeVisible()
    // the drawer starts collapsed (so the editor owns the height) — open it
    await panel.locator('.settings-json-reference-toggle').click()

    // hint line above the editor
    await expect(page.locator('.settings-json-hint')).toContainText('⌃Space')

    // app scope: app-only key present with a scope tag, and workspace-only key absent
    const themeRow = panel.locator('.settings-json-reference-row', { hasText: 'theme' }).first()
    await expect(themeRow).toBeVisible()
    await expect(themeRow.locator('.settings-json-reference-desc')).not.toBeEmpty()
    await expect(themeRow.locator('.settings-json-reference-scope')).toHaveText('app')

    const terminalShellRow = panel
      .locator('.settings-json-reference-row', { hasText: 'terminalShell' })
      .first()
    await expect(terminalShellRow.locator('.settings-json-reference-desc')).not.toBeEmpty()

    const notifyRow = panel
      .locator('.settings-json-reference-row', { hasText: 'notifications.onActionRequired' })
      .first()
    await expect(notifyRow).toBeVisible()
    await expect(notifyRow.locator('.settings-json-reference-scope')).toHaveText('both')

    // clicking a key copies a snippet and shows a confirmation tick
    await themeRow.click()
    await expect(themeRow.locator('.settings-json-reference-copied')).toBeVisible()

    // filter narrows the list (matches the key itself and its array-item sub-keys)
    const filter = panel.locator('.settings-json-reference-filter')
    const totalRows = await panel.locator('.settings-json-reference-row').count()
    await filter.fill('devProcesses')
    const narrowedRows = panel.locator('.settings-json-reference-row')
    await expect(narrowedRows).toHaveCount(4) // devProcesses, [].name, [].command, [].autoStart
    expect(await narrowedRows.count()).toBeLessThan(totalRows)
    await expect(
      panel.locator('.settings-json-reference-row', { hasText: 'devProcesses' }).first()
    ).toContainText('workspace')
    await filter.fill('')

    // switch to a workspace scope — the same panel appears there too
    await page.locator('.settings-content select.field').selectOption({ index: 1 })
    const wsPanel = page.locator('.settings-json-reference')
    await expect(wsPanel).toBeVisible()
    await wsPanel.locator('.settings-json-reference-toggle').click()
    const devRow = wsPanel
      .locator('.settings-json-reference-row', { hasText: 'devProcesses' })
      .first()
    await expect(devRow).toBeVisible()
    await expect(devRow.locator('.settings-json-reference-scope')).toHaveText('workspace')
  })

  test('typing a quote inside the object triggers schema autocomplete', async () => {
    launched = await launchApp()
    const { page } = launched
    await page.keyboard.press('Meta+k')
    await page.locator('.palette-input').fill('settings')
    await page.locator('.palette-input').press('Enter')
    await page.locator('.settings-nav-item', { hasText: 'settings.json' }).click()

    const host = page.locator('.settings-json-host')
    await expect(host).toBeVisible()
    await host.click()
    await page.keyboard.press('Meta+a')
    await page.keyboard.type('{\n  "')
    await expect(page.locator('.monaco-editor .suggest-widget.visible')).toBeVisible({
      timeout: 5000
    })
  })
})
